GCCFLAGS = -g

make: Vec3D.cpp Particle.cpp Gravity.cpp BHNode.cpp BHTree.cpp testing.cpp main.cpp
	g++ $(GCCFLAGS) Vec3D.cpp Particle.cpp Gravity.cpp BHNode.cpp BHTree.cpp testing.cpp main.cpp -o main
